name: Build Phantom DLL

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Show Project Files
        shell: cmd
        run: dir PhantomExec /s

      - name: Restore NuGet Packages
        run: nuget restore PhantomExec/Phantom.sln

      - name: Build DLL
        run: >
          msbuild PhantomExec/Phantom.sln
          /p:Configuration=Release
          /p:Platform=x64
          /m
          /verbosity:minimal

      - name: Verify Build Output
        shell: cmd
        run: |
          echo ===== Release Folder =====
          dir PhantomExec\Release

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: Phantom-Release-x64
          path: |
            PhantomExec/Release/Phantom.dll
            PhantomExec/Release/Phantom.lib
            PhantomExec/Release/Phantom.exp
            PhantomExec/Release/Phantom.pdb
          if-no-files-found: error
